import { primary, neutral, yellow, green, red } from './colors';
import { primaryFont, typeScale } from './typography';

export const defaultTheme = {
  bodyBackground: neutral[100],
  primaryColor: primary[100],
  primaryHoverColor: primary[200],
  primaryActiveColor: primary[300],
  formElementBackground: neutral[100],
  textOnFormElementBackground: neutral[600],
  textColorOnPrimary: neutral[100],
  textColor: neutral[600],
  textColorInverted: neutral[100],
  primaryFont: primaryFont,
  disabled: neutral[500],
  textOnDisabled: neutral[300],
  textFieldBackground: neutral[200],
  textFieldLabelColor: neutral[500],
  status: {
    warningColor: yellow[100],
    warningColorHover: yellow[200],
    warningColorActive: yellow[300],
    errorColor: red[100],
    errorColorHover: red[200],
    errorColorActive: red[300],
    successColor: green[100],
    successColorHover: green[200],
    successColorActive: green[300],
  },
  h1: typeScale.header1,
  h2: typeScale.header2,
  h3: typeScale.header3,
  h4: typeScale.header4,
  h5: typeScale.header5,
  p: typeScale.paragraph,
  copyright: typeScale.copyright,
  helperText: typeScale.helperText,
};
